### PR TITLE
Add formatting

### PR DESCRIPTION
**Pull request by dan8f**
Add Black formatter & CI check

### CODE REVIEW

**Review by MadMedian — APPROVED** [review]

**Review by MadMedian — CHANGES_REQUESTED** [review]
test

**Comment by timabilov** [comment]
i don't recommend having this big PR without having tests

**Comment by dan8f** [comment]
> i don't recommend having this big PR without having extensive tests. But from what i see if it is just quotes and line fitting, we can do it

Yes there is no logic changes. It is format

**Comment by MadMedian** [comment]
@dan8f could you please merge the other draft PR (with isort) into this one? Pls check my comments on the other one
We will squash merge and I would prefer to have all reformatting changes in a single commit.

**Pull request closed without merging**
